# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-06-01 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedules',
            name='from_hour',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedules',
            name='to_hour',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
